Update build-qbittorent-windows.yml

diff --git a/.github/workflows/build-qbittorent-windows.yml b/.github/workflows/build-qbittorent-windows.yml
--- a/.github/workflows/build-qbittorent-windows.yml
+++ b/.github/workflows/build-qbittorent-windows.yml
@@ -1,7 +1,3 @@
-# (modified for provenance verification)
-# qBittorrent yml for release (based on ci-windows.yml and the libtorrent version it was built upon is also reflected in the exe name)
-
-
 name: Build and Release qBittorrent Installer
 
 on:
@@ -226,11 +222,11 @@ jobs:
         shell: bash
         run: |
           if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
-  echo "release_tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
-else
-  echo "::error::This workflow must be triggered by a tag push to create a provenance badge."
-  exit 1
-fi
+            echo "release_tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
+          else
+            echo "::error::This workflow must be triggered by a tag push to create a provenance badge."
+            exit 1
+          fi
 
       - name: Create GitHub Release
         uses: softprops/action-gh-release@v2.1.0
